---
- hosts: all
  user: vagrant
  sudo: yes
  tasks:
    - name: install packages
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - vim
        - git
        - mysql-server
        - python
        - python-dev
        - python-pip
        - libxml2-dev
        - libxslt-dev
        - lib32z1-dev
        - zlib1g-dev

    - name: install python packages
      pip: name={{ item }}
      with_items:
        - bottle
        - lxml
        - requests
        - cssselect
        - six
        - chainer
        - numpy
